# Generated by Django 3.0.5 on 2020-04-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlbumApi', '0002_remove_artist_songs_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='number_of_songs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
